### ISSUE TITLE
Make content in JavaScript files translatable

### ISSUE THREAD

**Issue by sspj-does-weather** [weather-gov/weather.gov#2176]
### Description

While working on #2166 , it became clear that we need an additional mechanism to deal with content in JS files.

Drupal provides a JS library with a function `Drupal.t()` (note: it must be exactly `Drupal.t` and not minified by an outside bundler, because Drupal uses regex to locate this function) which can be enabled by setting it as a dependency in the yaml file:

```
front-page:
  version: 2024-09-03
  js:
    assets/js/front.page.js:
      attributes:
        type: module
        defer: true
  dependencies:
    - core/drupal
    - core/drupalSettings
```

However, [`Drupal.t`](https://git.drupalcode.org/project/drupal/-/blob/11.x/core/misc/drupal.js?ref_type=heads#L368-386) uses [`drupalTranslations`](https://git.drupalcode.org/project/drupal/-/blob/11.x/core/modules/locale/locale.module#L948) which in turn gets data from the [`locales_location`](https://git.drupalcode.org/project/drupal/-/blob/11.x/core/modules/locale/src/StringDatabaseStorage.php#L398-406) table in Drupal and requires strings be of type "javascript" which may be incompatible with our method of using .po files to import these strings.

An alternative is to translate content in PHP and pass it to the JavaScript.

### Acceptance Criteria
- [ ] JavaScript content is able to be translated
- [ ] Strings in JS are in [this sheet](https://docs.google.com/spreadsheets/d/1xsCSnnQ9m4BIHCGbP6GGgMz95VKHQQvOvkbedyaLLm8/edit) 🔒 for translation
